task :create_rules do
  require File.expand_path('../../../config/environment', __FILE__)

  rules_info = [
    ["Talking about his parents' relationship",5],
    ['Mentioning his kid',5],
    ['Mentioning a deceased loved one',10],
    ['Mentioning a previous fiancee or wife',10],
    ['Expressing fear of a date activity',10],
    ['Discussing his virginity',15],
    ['Saying "Im not here to make friends"',20],
    ['Saying "I am falling for you" to the Bachelorette or "I am falling for her" to the camera',20],
    ['Saying "I love you" to the Bachelorette',30],
    ['Telling the Bachelorette that someone in the house "is not here for the right reasons"',30],
    ['Being told "I love you" by the Bachelorette',50],
    ["Interrupting someone's one-on-one time",5],
    ['Using the phrase "steal [the Bachelorette], away" during a one-on-one interruption',5],
    ['Dancing',5],
    ['Wearing a helmet',5],
    ['Singing or playing an instrument for the Bachelorette',5],
    ['Hot tubbing',5],
    ['Giving the Bachelorette a gift',5],
    ['Going on a picnic',5],
    ['Wearing a costume or clothing native to another culture/country',5],
    ['Attending a concert',10],
    ['Riding in a helicopter',10],
    ['Riding on a boat',10],
    ['Kissing the Bachelorette on the lips',10],
    ['Being apart of the "team" who wins alone time with the Bachelorette on a group date',15],
    ['Appearing visibly drunk',15],
    ["Meeting the Bachelorette's family and/or friends",15],
    ['Interrupting a rose ceremony to ask to speak with the Bachelorette alone',20],
    ['Needing medical attention at any point',20],
    ['Crying on camera',25],
    ['Having a secret girlfriend at home',25],
    ['Having a body part blurred out any point',30],
    ['Leaving the show early on his own accord',30],
    ['Drafting the next Bachelor on your team',40],
    ['Coming back to the show to beg for another chance',50],
    ['Getting the First Impression Rose',35],
    ['Being selected to go on a group date',10],
    ['Being selected to go on a one-on-one date',20],
    ['Being selected to go on a two-on-one date',30],
    ['Getting the rose to stay another week',25],
    ['Getting the rose on a group date', 35],
    ['Getting the rose on a two-on-one date',40],
    ['Making it to Hometown Dates',50],
    ['Accepting the Fantasy Suite',75],
    ['Refusing the Fantasy Suite when the Bachelorette is game',-75],
    ['Proposing or being proposed to',85],
    ['Winning the Final Rose',100]
  ]
  rules_info.each do |rule_info|
    Rule.create(description: rule_info[0], points: rule_info[1])
  end
end
